# Generated by Django 5.2.1 on 2025-05-22 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação da Chat.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização da Chat.')),
                ('participants', models.ManyToManyField(help_text='Usuários participantes desta Chat.', related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a mensagem foi enviada.')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('location', 'Local de Troca'), ('suggestion', 'Sugestão de Troca')], default='text', help_text='Tipo da mensagem (texto, local de troca, sugestão de troca).', max_length=10)),
                ('text_content', models.TextField(blank=True, help_text="Conteúdo textual da mensagem (se for do tipo 'texto').", null=True)),
                ('location_data', models.TextField(blank=True, help_text="Dados do local de troca (se for do tipo 'local de troca').", null=True)),
                ('suggestion_data', models.TextField(blank=True, help_text="Dados da sugestão de troca (se for do tipo 'sugestão de troca').", null=True)),
                ('Chat', models.ForeignKey(help_text='A Chat à qual esta mensagem pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat')),
                ('sender', models.ForeignKey(help_text='O usuário que enviou esta mensagem.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['horario'],
            },
        ),
    ]
