# Generated by Django 5.2.1 on 2025-05-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_options_remove_chat_participants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Chat',
            new_name='chat',
        ),
    ]
