# Generated by Django 5.2.1 on 2025-05-30 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chat_user_chat_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='exchange_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='exchange_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_exchanges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='location_confirmed',
            field=models.BooleanField(default=False, help_text='Indica se o local de troca nesta mensagem foi confirmado.'),
        ),
        migrations.AddField(
            model_name='message',
            name='location_confirmed_by',
            field=models.ForeignKey(blank=True, help_text='O usuário que confirmou o local de troca.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
