# Generated by Django 5.2.1 on 2025-05-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_exchange_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='exchange_confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='location_confirmed',
            field=models.BooleanField(default=False, help_text='Indica se o local de troca nesta mensagem foi confirmado.', null=True),
        ),
    ]
