# Generated by Django 5.2.1 on 2025-05-17 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0001_initial'),
        ('stickers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='album_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='albuns.album'),
        ),
    ]
