# Generated by Django 5.2.1 on 2025-05-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0002_sticker_album_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sticker',
            old_name='album_id',
            new_name='album',
        ),
        migrations.AddField(
            model_name='sticker',
            name='number',
            field=models.IntegerField(default=958),
        ),
    ]
