# Generated by Django 5.2.1 on 2025-05-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0003_rename_album_id_sticker_album_sticker_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sticker',
            old_name='album',
            new_name='album_id',
        ),
        migrations.AddField(
            model_name='sticker',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='number',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
