# Generated by Django 5.2.1 on 2025-05-20 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0004_rename_album_sticker_album_id_sticker_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sticker',
            old_name='album_id',
            new_name='album',
        ),
    ]
