# Generated by Django 5.2.1 on 2025-05-27 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0001_initial'),
        ('sticker_groups', '0001_initial'),
        ('stickers', '0005_rename_album_id_sticker_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='sticker_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sticker_groups.stickergroup'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='albuns.album'),
        ),
    ]
