# Generated by Django 5.2.1 on 2025-05-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0006_sticker_sticker_group_alter_sticker_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='number',
        ),
        migrations.AddField(
            model_name='sticker',
            name='text',
            field=models.CharField(default='', max_length=50),
        ),
    ]
