# Generated by Django 5.2.1 on 2025-05-28 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0007_remove_sticker_number_sticker_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='country',
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='type',
        ),
    ]
