# Generated by Django 5.2.1 on 2025-05-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0008_remove_sticker_country_remove_sticker_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
