# Generated by Django 5.2.1 on 2025-05-29 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0001_initial'),
        ('sticker_groups', '0002_auto_20250528_2237'),
        ('stickers', '0009_alter_sticker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='albuns.album'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='sticker_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sticker_groups.stickergroup'),
        ),
    ]
